{
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

   "distributed_backend": "nccl",

   "lr_decay_style": "cosine",
   "extra_save_iters": [1],
   "eval_iters": 75,

   "log_interval": 1,
   "steps_per_print": 1,
   "wall_clock_breakdown": true,

   "tokenizer_type": "HFTokenizer",
   "vocab-file": "/home/za2514/compute/pythia_tokenizer/tokenizer.json",

   "use_wandb": true,
   "wandb_project": "hparam-0.1",
   "wandb_team": "math-lm",
   "wandb_host": "https://api.wandb.ai",
   
   "train-data-paths": ["/home/za2514/compute/data/pile_llama/train/pile-sample/pile-sample_text_document"],
   "valid-data-paths": ["/home/za2514/compute/data/pile_llama/validation/pile-sample/pile-sample_text_document"],
   "test-data-paths": ["/home/za2514/compute/data/pile_llama/test/pile-sample/pile-sample_text_document"],
}
