{
  "train_micro_batch_size_per_gpu": 2048,
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,
  "distributed_backend": "gloo",
  "num_gpus": 16,
  "num_layers": 32,
  "hidden_size": 2560,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "norm": "layernorm",
  "pos_emb": "rotary",
  "no_weight_tying": True,
  "data_impl": "mmap",
  "train_iters": 100,
  "lr_decay_iters": 100,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.01,
  "save_interval": 1000,
  "eval_interval": 1000,
  "eval_iters": 10,
  "train_data_paths": ["/fsx/pile/pile_20B_tokenizer_text_document"],
  "valid_data_paths": ["/fsx/pile/pile_20B_tokenizer_text_document"],
  "test_data_paths": ["/fsx/pile/pile_20B_tokenizer_text_document"],
  "tokenizer_type": "HFTokenizer",
  "vocab_file": "/fsx/pile/20B_tokenizer.json",
  "hostfile": "/fsx/orz/gpt-neox-memorization/hosts",
  "iteration": 0,
}