{
  "test-data-paths": ["data/pile/shard_0/shard_0_text_document"],
  "test-data-weights": [
    1.
  ],
  "valid-data-paths": [
    ["data/pile/shard_0/shard_0_text_document"],
  ],
  "valid-data-weights": [
    [1.],
  ],
  "val-dataset-name": 'pile_val_shard0',
}
