{
  "data_path": "/admin/home-jinwooahn/repos/data/bpe_50k/small_text_document",
  "vocab_file": "/fsx/polyglot-korean/tokenizer/polyglot_bpe_50k.json",
  "save": "/fsx/polyglot-korean/checkpoints/6-9B",
  "checkpoint_validation_with_forward_pass": false,
  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "launcher": "slurm",
  "deepspeed_slurm": true,
  "no_ssh_check": true,
  "use_wandb": true,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "polyglot-v2-1-4b",
}
