{
  "data_path": "/fsx/home-geonil/small_exp/merge_data/small_exp_50B",
  "data_impl": "mmap",
  "vocab_file": "/fsx/polyglot-korean/tokenizer/polyglot_bpe_50k.json",
  #"save": "/admin/home-jinwooahn/repos/checkpoints/small-scale-12B",
  #"s3_path": "s3://polyglot-korean-west/checkpoints/small-scale-12B",  # currently raising error..
  "checkpoint_validation_with_forward_pass": false,
  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "launcher": "slurm",
  "deepspeed_slurm": true,
  "no_ssh_check": true,
  "use_wandb": true,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "polyglot-v2-12B-small-scale"
}
