{
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,

  "num_layers": 6,
  "hidden_size": 512,
  "num_attention_heads": 8,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",

  "attention_config": [[["flash"], 6]],

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": true,

  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.001,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },
  "min_lr": 0.0001,

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

  "train_micro_batch_size_per_gpu": 64,
  "gas": 2,
  "data_impl": "mmap",
  "num_workers": 1,

  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

   "distributed_backend": "nccl",

   "train_iters": 512,
   "lr_decay_iters": 512,
   "lr_decay_style": "cosine",
   "warmup_iter": 100,
   "checkpoint_factor": 512,
   "extra_save_iters": [1],
   "eval_interval": 128,
   "eval_iters": 50,

   "log_interval": 1,
   "steps_per_print": 1,
   "wall_clock_breakdown": true,

   "tokenizer_type": "HFTokenizer",
   "vocab-file": "/home/za2514/compute/pythia_tokenizer/tokenizer.json",

   "save": "/home/za2514/compute/saved-weights/scaling-0.1/",

   "log-dir": "/home/za2514/compute/scaling/gpt-neox/logs/scaling-0.1",

   "use_wandb": true,
   "wandb_group": "70M-512step",
   "wandb_project": "scaling-0.1",
   "wandb_team": "math-lm",
   "wandb_host": "https://api.wandb.ai",
   
   "train-data-paths": ["/home/za2514/compute/data/proof-pile_llama/train/arxiv-rp/arxiv-rp_text_document"],
   "valid-data-paths": ["/home/za2514/compute/data/proof-pile_llama/validation/arxiv-rp/arxiv-rp_text_document"],
   "test-data-paths": ["/home/za2514/compute/data/proof-pile_llama/test/arxiv-rp/arxiv-rp_text_document"]
}
