{
  "pipe_parallel_size": 0,
  "model_parallel_size": 2,
  "make_vocab_size_divisible_by": 1,

  # model settings
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 4096,
  "max_position_embeddings": 4096,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,

  "attention_config": [[["flash"], 32]],

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",

   "optimizer": {
     "type": "Adam",
     "params": {
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },

   "min_lr": 0.0,

   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

   "train_micro_batch_size_per_gpu": 4,
   "data_impl": "mmap",

   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   "gradient_clipping": 1,
   "gradient_accumulation_steps": 1,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,
    
   "precision": "bfloat16",
   "bf16": {
       "enabled": true,
   }, 
   "fp16": {
       "enabled": false,
   },
   "data_types": {
       "grad_accum_dtype": "fp32",
   }, 
   "fp32_allreduce": true,

   "decay_lr_to": 0.1,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup_iters": 1,
   "checkpoint_factor": 100,
   "eval_interval": 50,
   "eval_iters": 1,

   "log_interval": 1,
   "steps_per_print": 1,
   "wall_clock_breakdown": true,

   "tokenizer_type": "SPMTokenizer",
   "vocab-file": "/home/za2514/compute/codellama/tokenizer.model",

   "load": "/nobackup/scratch/usr/za2514/downloaded-weights/llemma_7b",
   "finetune": true,
   "override_lr_scheduler": true,
   
   "train-data-paths": ["/nobackup/scratch/usr/za2514/data/llemma-instruct-2/train/muinstruct/muinstruct_text_document", "/nobackup/scratch/usr/za2514/data/llemma-instruct-2/train/camel-math/camel-math_text_document"],
   "label-data-paths": ["/nobackup/scratch/usr/za2514/data/llemma-instruct-2/train/muinstruct/muinstruct_label_document", "/nobackup/scratch/usr/za2514/data/llemma-instruct-2/train/camel-math/camel-math_label_document"],
   "train-data-weights": [0.2, 0.8],
   "valid-data-paths": ["/nobackup/scratch/usr/za2514/data/llemma-instruct-2/train/muinstruct/muinstruct_text_document"],
   "test-data-paths": ["/nobackup/scratch/usr/za2514/data/llemma-instruct-2/train/muinstruct/muinstruct_text_document"],

   "use_wandb": true,
   "wandb_project": "llemma-instruct",
   "wandb_host": "https://api.wandb.ai",
   "log_param_norm": true
}
