{
  "pipe_parallel_size": 0,
  "model_parallel_size": 2,
  "make_vocab_size_divisible_by": 1,

  # model settings
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,

  "attention_config": [[["flash"], 32]],

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.00003,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },

   "min_lr": 0.000003,

   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

   "train_micro_batch_size_per_gpu": 8,
   "gradient_accumulation_steps": 4,
   "data_impl": "mmap",

   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   "train_iters": 10000,
   "lr_decay_iters": 10000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.04,
   "checkpoint_factor": 5000,
   "eval_interval": 1000,
   "eval_iters": 50,

   "log_interval": 10,
   "steps_per_print": 5,
   "wall_clock_breakdown": true,

   "tokenizer_type": "SPMTokenizer",
   "vocab-file": "/fsx/proj-mathlm/pretrained-weights/llama/tokenizer.model",

   "save": "/fsx/proj-mathlm/saved-weights/llama_7b_test_thruput",
   #"load": "/fsx/proj-mathlm/pretrained-weights/llama_neox/7B_mp2/",
   "finetune": true,
   "no_load_optim": true,
   "override_lr_scheduler": true,
   #"checkpoint_validation_with_forward_pass": true,
   

   #"data-path": "/fsx/hailey/math-lm/gpt-neox/enwik8/enwik8/enwik8_text_document",
   "train-data-paths": ["/fsx/proj-mathlm/data/proof-pile_llama/train/arxiv-rp/arxiv-rp_text_document"], # "/fsx/proj-mathlm/data/proof-pile_llama/train/pile-sample/pile-sample_text_document"],
   #"train_data_weights": [0.95, 0.05],
   "valid-data-paths": ["/fsx/proj-mathlm/data/proof-pile_llama/validation/arxiv-rp/arxiv-rp_text_document"],
   "test-data-paths": ["/fsx/proj-mathlm/data/proof-pile_llama/validation/arxiv-rp/arxiv-rp_text_document"], # avoid touching the test set!

   #"tensorboard-dir": "/home/za2514/tensorboard",
   "log-dir": "logs/v0.8/llama_7b_arxiv-rp_short",

   "use_wandb": true,
   "wandb_group": "llama_7b_arxiv-rp_short",
   "wandb_project": "math-lm-v0.8",
   "wandb_host": "https://api.wandb.ai",

   "launcher": "slurm",
   "deepspeed_slurm": true
}
