{
   "pipe_parallel_size": 1,
   "model_parallel_size": 2,

   "num_layers": 32,
   "hidden_size": 4096,
   "num_attention_heads": 32,
   "seq_length": 2048,
   "max_position_embeddings": 2048,
   "norm": "layernorm",
   "pos_emb": "rotary",
   "rotary_pct": 0.25,
   "no_weight_tying": true,
   "gpt_j_residual": true,
   "output_layer_parallelism": "column",

   "attention_config": [[["flash"], 32]],

   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.00006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },

   "min_lr": 0.000006,

   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

   "train_micro_batch_size_per_gpu": 8,
   "gradient_accumulation_steps": 4,
   "data_impl": "mmap",

   "checkpoint_activations": true,
   "checkpoint_num_layers": 1,
   "partition_activations": true,
   "synchronize_each_layer": true,

   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,

   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   "train_iters": 120000,
   "lr_decay_iters": 120000,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 10000,
   "eval_interval": 1000,
   "eval_iters": 100,

   "log_interval": 10,
   "steps_per_print": 10,
   "wall_clock_breakdown": true,

   "tokenizer_type": "HFTokenizer",
   "vocab-file": "/home/za2514/tokenizer/20B_tokenizer.json",

   "save": "/home/za2514/saved-weights/proofgpt-v0.5/proofgpt-v0.5-6.9b-1epoch-flash",
   
   "train-data-paths": ["/home/za2514/proof-pile-v2/train/proof-pile/proof-pile_text_document", "/home/za2514/proof-pile-v2/train/pile-sample/pile-sample_text_document"],
   "valid-data-paths": ["/home/za2514/proof-pile-v2/validation/proof-pile/proof-pile_text_document"],
   "test-data-paths": ["/home/za2514/proof-pile-v2/test/proof-pile/proof-pile_text_document"],

   "tensorboard-dir": "/home/za2514/tensorboard",
   "log-dir": "/home/za2514/logs",

   "use_wandb": false,
   "wandb_group": "v0.5-6.9b_flash",
   "wandb_project": "math-lm-v0.5",
   "wandb_host": "https://api.wandb.ai",
}
