kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eleuther-ssd-cluster
  namespace: tenant-eleutherai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: shared-nvme-ord1
  volumeMode: Filesystem
