{
   "pipe-parallel-size": 1,
   "model-parallel-size": 8,

   "num-layers": 16,
   "hidden-size": 12288,
   "num-attention-heads": 96,
   "seq-length": 4096,
   "max-position-embeddings": 4096,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "rotary_pct": 0.25,
   "no-weight-tying": true,
   "gpt_j_residual": true,
   "output_layer_parallelism": "column",

   "attention-config": [[["flash"], 16]],

   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-6
     }
   },
   "min_lr": 0.00006,

   "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 12600000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

   "train_micro_batch_size_per_gpu": 16,
   "gradient_accumulation_steps": 1,
   "data-impl": "mmap",

   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.2,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   "train-iters": 10,
   "lr-decay-iters": 360000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 1000,
   "eval-interval": 4000,
   "eval-iters": 10,

   "log-interval": 10,
   "steps_per_print": 10,
   "wall_clock_breakdown": true,

   "use_wandb": false,
   "data-path": "/fsx/users/leecheng/sai/gpt-neox/data/enwik8/enwik8_text_document",
   "vocab-file": "/fsx/users/leecheng/sai/gpt-neox/data/gpt2-vocab.json",
   "merge-file": "/fsx/users/leecheng/sai/gpt-neox/data/gpt2-merges.txt",
   
   "launcher": "openmpi",
   "deepspeed_mpi": true,
   "hostfile": "/fsx/users/frodo/hostfile_mpi"
}
