# Data paths and options when using EleutherAI cluster
{
  # or for weighted datasets:
  "train-data-paths": ["/mnt/neox/data/enron/enron_text_document"]
  "test-data-paths": ["/mnt/neox/data/enron/enron_text_document"],
  "valid-data-paths": ["/mnt/neox/data/enron/enron_text_document"],

  "vocab-file": "/mnt/neox/data/gpt2-vocab.json",
  "merge-file": "/mnt/neox/data/gpt2-merges.txt",
  "save": "/mnt/neox/checkpoints/pythia",
  "load": "/mnt/neox/checkpoints/pythia",
  "tensorboard-dir": "/mnt/neox/tensorboard",
  "log-dir": "/mnt/neox/logs",
  "wandb_team": "pythia",
}
