# Data paths and options when using EleutherAI cluster
{

  "train-data-paths": ["/mnt/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_text_document"],
  "valid-data-paths": ["/mnt/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_valid_text_document"],
  "test-data-paths": ["/mnt/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_test_text_document"],
  
  "tokenizer_type": "HFTokenizer",
  "vocab-file": "/mnt/neox/data/20B_tokenizer.json",
  
  "vocab-file": "/mnt/neox/data/gpt2-vocab.json",
  "merge-file": "/mnt/neox/data/gpt2-merges.txt",
  
  "save": "/mnt/neox/checkpoints/pythia",
  "load": "/mnt/neox/checkpoints/pythia",
  "tensorboard-dir": "/mnt/neox/tensorboard",
  "log-dir": "/mnt/neox/logs",
  "wandb_team": "pythia",
}
