# Data paths and options when using EleutherAI cluster
{
  "train-data-paths": ["/mnt/ssd/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_text_document"],
  "valid-data-paths": ["/mnt/ssd/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_val_text_document"],
  "test-data-paths": ["/mnt/ssd/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_test_text_document"],

  "tokenizer_type": "HFTokenizer",
  "vocab-file": "/mnt/ssd/neox/data/20B_tokenizer.json",

  "save": "/mnt/ssd/neox/checkpoints/pythia/13B-decay",
  "load": "/mnt/ssd/neox/checkpoints/pythia/13B-decay",
  "tensorboard-dir": "/mnt/ssd/neox/tensorboard",
  "log-dir": "/mnt/ssd/neox/logs",
  "wandb_team": "eleutherai",
  "wandb_project": "pythia",
  "wandb_group": "13B Decay"
}
