# Data paths and options when using EleutherAI cluster
{
  "train-data-paths": ["/mnt/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_text_document"],
  "valid-data-paths": ["/mnt/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_val_text_document"],
  "test-data-paths": ["/mnt/neox/data/pile_20B_tokenizer/pile_20B_tokenizer_test_text_document"],
  
  "tokenizer_type": "HFTokenizer",
  "vocab-file": "/mnt/neox/data/20B_tokenizer.json",
  
  "save": "/mnt/neox/checkpoints/pythia/2-7B",
  "load": "/mnt/neox/checkpoints/pythia/2-7B",
  "tensorboard-dir": "/mnt/neox/tensorboard",
  "log-dir": "/mnt/neox/logs",
  "wandb_team": "eleutherai",
  "wandb_project": "pythia",
  "wandb_group": "2-7B"
}
