# Data paths and options when using EleutherAI cluster
{
  "train-data-paths": ["/mnt/ssd-1/data/enron/enron_train_text_document"],
  "valid-data-paths": ["/mnt/ssd-1/data/enron/enron_val_text_document"],
  "test-data-paths": ["/mnt/ssd-1/data/enron/enron_test_text_document"],

  "vocab-file": "/mnt/ssd-1/data/gpt2-vocab.json",
  "merge-file": "/mnt/ssd-1/data/gpt2-merges.txt",
  "save": "/mnt/ssd-1/checkpoints",
  "load": "/mnt/ssd-1/checkpoints",
  "tensorboard-dir": "/mnt/ssd-1/tensorboard",
  "log-dir": "/mnt/ssd-1/logs",
  "wandb_team": "eleutherai",
  "wandb_project": "neox",
  "wandb_group": "example"
}
