{
   "pipe-parallel-size": 1,
   "model-parallel-size": 4,

   "num-layers": 36,
   "hidden-size": 8192,
   "num-attention-heads": 64,
   "seq-length": 4096,
   "max-position-embeddings": 4096,
   "norm": "layernorm",
   "pos-emb": "rotary",
   "rotary_pct": 0.25,
   "no-weight-tying": true,
   "gpt_j_residual": true,
   "output_layer_parallelism": "column",

   "attention-config": [[["flash"], 36]],

   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-6
     }
   },
   "min_lr": 0.00006,

   "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 1260000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1260000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },

   "train_micro_batch_size_per_gpu": 16,
   "gradient_accumulation_steps": 1,
   "data-impl": "mmap",

   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,
   "extra-save-iters": [500, 1500],

   "gradient_clipping": 1.0,
   "weight-decay": 0.2,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   "fp16": {
     "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   "train-iters": 360000,
   "lr-decay-iters": 360000,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 50,
   "eval-interval": 2000,
   "eval-iters": 10,
   "save": "/fsx/ckpts/neox-30b-2",
   "load": "/fsx/ckpts/neox-30b-2",

   "log-interval": 10,
   "steps_per_print": 10,
   "wall_clock_breakdown": true,

   "train-data-paths": [ "/fsx/proj-stablegpt/pilev2_neox/ai4code_nbs/ai4code_nbs_input_ids_document"],
  "train-data-weights": [1.0],
  "valid-data-paths": ["/fsx/proj-stablegpt/pilev2_neox/ai4code_nbs/ai4code_nbs_input_ids_document"],
  "valid-data-weights": [1.0],
  "test-data-paths": ["/fsx/proj-stablegpt/pilev2_neox/ai4code_nbs/ai4code_nbs_input_ids_document"],
  "test-data-weights": [1.0],

   "tokenizer_type": "TiktokenTokenizer",
   "vocab-file": "cl100k_base",

   "use_wandb": true,
   "wandb_host": "https://stability.wandb.io",
   "wandb_team": "shiv",
   "wandb_project": "30B",
   "wandb_group": "30B-pilev2-correct",

   "launcher": "slurm",
   "deepspeed_slurm": true
}
