# Data paths and options when using EleutherAI cluster
{
  "train-data-paths": ["/fsx/pile/pile_20B_tokenizer_text_document"],
  "valid-data-paths": ["/fsx/pile/pile_20B_tokenizer_text_document"],
  "test-data-paths": ["/fsx/pile/pile_20B_tokenizer_text_document"],

  "tokenizer_type": "HFTokenizer",
  "vocab-file": "/fsx/pile/20B_tokenizer.json",
  "load": "/fsx/orz/gpt-neox/checkpoints/",
  "log-dir": "/fsx/orz/gpt-neox/logs",
  "wandb_team": "eleutherai",
  "wandb_project": "memorization-6.7B",
  "wandb_group": "6.7B",
  "sample-output-file":"/fsx/orz/gpt-neox/sampleoutput.txt",
  "text-gen-type": "unconditional",
  "maximum_tokens": 64,
  "temperature": 0.0,
  "top_p": 0.0,
  "top_k": 0,
  "recompute": false,

  "num-samples": 10,
  "hostfile": "/fsx/orz/gpt-neox/hosts",
  "launcher": "openmpi",
  "deepspeed_mpi": true
}