# Data paths and options
# Replace /PATH/HERE/ with the path to our mounted drive

{
  "data-path": "/PATH/HERE/data/enron/enron_text_document",
  "vocab-file": "/PATH/HERE/data/gpt2-vocab.json",
  "merge-file": "/PATH/HERE/data/gpt2-merges.txt",
  "save": "/PATH/HERE/checkpoints",
  "load": "/PATH/HERE/checkpoints",
  "tensorboard-dir": "/PATH/HERE/tensorboard",
  "log-dir": "/PATH/HERE/logs",
}
