# Suggested data paths when using GPT-NeoX locally
{
  "train-data-paths": "/gpfs/alpine/csc499/proj-shared/LAION-400m-webdataset/data/{00000..40000}.tar",
  "valid-data-paths": "/gpfs/alpine/csc499/proj-shared/LAION-400m-webdataset/data/{40001..41000}.tar", 
  "test-data-paths": "/gpfs/alpine/csc499/proj-shared/LAION-400m-webdataset/data/{41000..41455}.tar", 


  "vocab-file": "./data/20B_tokenizer.json",

  
  "save": "/gpfs/alpine/scratch/lfsm/csc499/checkpoints",
  "load": "/gpfs/alpine/scratch/lfsm/csc499/checkpoints",
  # separate load path for pretrained clip, same with 'load' in this case
  "load_clip": "/gpfs/alpine/scratch/lfsm/csc499/checkpoints",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "/gpfs/alpine/scratch/lfsm/csc499/tensorboard",
  "log-dir": "/gpfs/alpine/scratch/lfsm/csc499/logs",
  "use_wandb": False,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox",

  "launcher": "jsrun",
  "deepspeed_jsrun": true,

}
