name: "Run CPU Tests"

on: "push"

jobs:
  run-tests:
    #runs-on: ubuntu-latest
    runs-on: [ 'test', 'self-hosted' ]
    # container:
    #   image: amr-registry.caas.intel.com/aiops/aikit-products-dev:2024.1.0
    #   options: --privileged
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Set up Docker repository
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          
          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: Docker installation
        run: |
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo docker run hello-world
      
      - name: Docker testing
        run: |
          sudo docker run hello-world

      - name: Testing containers
        run: |
          docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
          pwd
          export NEOX_DATA_PATH=/mnt/sda/data/enwiki8 #or wherever your data is stored on your system
          export NEOX_CHECKPOINT_PATH=/mnt/sda/checkpoints

      # - name: Install Dependencies
      #   run: |
      #     sudo apt-get install libopenmpi-dev -y
      #     pip install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu
      #     pip install -r requirements/requirements.txt
      #     pip install -r requirements/requirements-dev.txt
      #     pip install -r requirements/requirements-wandb.txt

      - name: Prepare Data
        run: python prepare_data.py

      - name: Run CPU Tests
        run: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python pytest tests -m cpu
